### ISSUE TITLE
Conversion of PWG to SLP1

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/PWG#11]
The base version of pwg (the one subject to corrections), is now pwg_orig_utf8_slp1.txt, rather then the former base version pwg_orig_utf8.txt.

The primary difference is that for the devanagari text {#X#} , X is coded in SLP1.

Two secondary differences are:
a. the coding errors of M or H plus accent have been corrected in this conversion
b. the use of ellipsis for space in bracketed {} text has been changed, so that spaces are used directly.

The primary programs and transcoder files used in this conversion are in this repository in the directory https://github.com/sanskrit-lexicon/PWG/tree/master/convertwork.

The readme.txt file therein summarizes some of the technical problems encountered.

**Comment by gasyoun** [comment]
@funderburkjim as of https://github.com/sanskrit-lexicon/CORRECTIONS/issues/7#issuecomment-89058657 can we consider this thread closed?
