### ISSUE TITLE
Rudiments of pre-SLP1 Stage

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/PWG#15]
In the quest for `Sruz
`
im Zend `c2` = `ç`, but it's not converted. I guess there must be a lot more of the same kind.

![zend](https://cloud.githubusercontent.com/assets/80761/5857535/9f7168c8-a25d-11e4-940d-3e56c15d5eb6.PNG)

**Comment by funderburkjim** [comment]
This c2 is converted in the display, but not in the digitization pwg.txt or pwg.xml.
Check the display for Sruz.

**Comment by gasyoun** [comment]
I do worry more about the source files. Display is great, but we must think of the portability. Should not we have it fixed in the source file or you are afraid of something I'm not aware of?

**Comment by drdhaval2785** [comment]
source file pwg.txt now has corrected version in IAST.

`Vgl. <is>aśrusti</is>, <is>śraoṣa</is> im Zend`
