### ISSUE TITLE
Possible misc Russian in PWG

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/PWG#17]
Sampada is currently  working on filling in missing data in PWG.

Under [antarveDa](http://www.sanskrit-lexicon.uni-koeln.de/scans/PWGScan/2013/web/webtc/indexcaller.php?key=antarveDa&input=slp1&output=deva),
one of the missing pieces occurred in text which may be in Cyrillic characters; Peter thought it might
be Polish.

old xml: (Note: the text is filled in - I think in the original digitization pwg.txt,  the data entry person
thought it was Greek, and entered some transliterated version of Greek.

```
<H1><h><key1>antarveDa</key1><key2>antarveDa</key2></h><body>N. pr. einer Localität 
<ls>Verz. d. Oxf. H. 338,b,23. 339,a,47.b,37</ls> <s>(antararveDa). °deSa</s> <ls>352,b,10.</ls> 
Vgl. <ls><lang n="Russian">AHTapao4}a</lang> bei WASSILJEW 55.</ls></body><tail>
<L>63904</L><pc>5-0998</pc></tail></H1>
```

new xml:

```
<H1><h><key1>antarveDa</key1><key2>antarveDa</key2></h><body>N. pr. einer Localität 
<ls>Verz. d. Oxf. H. 338,b,23. 339,a,47.b,37</ls> <s>(antararveDa). °deSa</s> <ls>352,b,10.</ls> 
Vgl. <ls><lang n="Russian">AHTapao4}a</lang> bei WASSILJEW 55.</ls></body><tail>
<L>63904</L><pc>5-0998</pc></tail></H1>
```

It this is Russian, the correct Cyrillic needs to be entered.

**Comment by drdhaval2785** [comment]
No chance of having her on github?

**Comment by gasyoun** [comment]
Антарабида - it's Russian. Polish does not use Cyrillic letters.

**Comment by gasyoun** [comment]
@funderburkjim fixed?

**Comment by drdhaval2785** [comment]
```
<lang n="russian">Антарабида</lang> bei <ls>WASSILJEW 55.</ls>
```
Included in pwg.txt.
