### ISSUE TITLE
Page numbers clickable

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/PWG#25]
In http://www.sanskrit-lexicon.uni-koeln.de/scans/PWGScan/2013/web/webtc/indexcaller.php aja

we have `— f) (in Folge einer gezwungenen Erklärung) eine Art Getreide: tatra (śrutau) kilaitaduktam  [Page01.0067]  . ajairyaṣṭavyamiti .` where `[Page01.0067] ` is not clickable, but should be, I guess.

**Comment by Andhrabharati** [comment]
@drdhaval2785 
Jim had made all the [Page...] links clickable recently across all dictionaries; thus this issue could be closed.
