### ISSUE TITLE
Scansion Symbols [Metrum, a: {Ç} {Ç} b. c. d: {Ç}]

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/PWG#29]
```
Metrum, a: {Ç} {Ç} b. c. d: {Ç} 
```

https://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/servepdf.php?dict=pwg&page=5-0101 in buddhi

`{Ç}` is to be replaced with [symbols](https://en.wikipedia.org/wiki/Scansion). After reading http://unicode.org/L2/L2011/11210-metrical-symbols.pdf I understand that to make it look 1 to 1 is impossible. I can go through all instances of `{Ç}`  if we decide what to replace it with.

Like

```
˘ ˘ ˘ – – –
```

It's fine in another entry:

```
15) N. eines Metrums, = cakrapāta (4 Mal ¯ ˘ ˘ ˘ ˘ ˘ ˘ ˘ ˘ ˘ ˘ ˘ ˘ ¯) Colebr. Misc. Ess. II, 161   (IX, 17).  
```

**Comment by Andhrabharati** [comment]
I am doing this now (half way through), and will be posting by tomorrow.

You will be surprised to see the characters I used, which are very close to the print, @gasyoun.
[I just went beyond boundaries to get them!]

The Breve and Macron that @funderburkjim proposed elsewhere are the traditional approach.
Breve and Macron do not have the same width and do not fit to be side-by-side aesthetically.
Also they look hanging in the sky, instead of sitting in the middle along with other letters (words) within the line x-height.

**Comment by Andhrabharati** [comment]
Here is a screenshot of a portion of the work.
![image](https://user-images.githubusercontent.com/75209130/119251072-0f51ca00-bbc2-11eb-967c-747379a80099.png)

Seen that there are two types of these {Ç} cases-
1. resp. characters unfilled, the position being indicated by {Ç}
2. resp. characters filled up, but {Ç} retained

On the whole, there are 126 such lines in the full pwg.txt file.
    `----------------------`
At `<L>13998<pc>1-1134<k1>OpacCandasika<k2>OpacCandasika,`
these characters were filled up with other characters (1) minus or n-dash in place of macron, (2) small o in place of breve.
> <ls>?(2 Mal 16 + 18</ls> Moren; Ausgang -o- und o—) 
> 

These are to be appropriately corrected as done in {Ç} lines.

And finally if the above characters I suggested are agreed upon by others, all places having the breve and macron for the guru and laghu characters could also be similarly changed.

**Comment by Andhrabharati** [comment]
I have filled up all the Ç lines yesterday itself (a portion which was pasted in my prev. message); but then I happened to notice many of them were already been done by some one over 6 years back and the files are lying in the CORRECTIONS\dictionaries\PWG\missing folder, waiting for further action.

Guess @gasyoun isn't aware of this earlier work, as he had proposed (by raising this issue) to do it 2 years back.

But whatever is it, I am happy that I had found 2 good-looking characters to be used in the prosodial texts.

**Comment by gasyoun** [comment]
> And finally, if the above characters I suggested are agreed upon by others

Have nothing against them.

> isn't aware of this earlier work, as he had proposed (by raising this issue) to do it 2 years back

Was not aware. Was @funderburkjim aware?

**Comment by Andhrabharati** [comment]
@funderburkjim,

it's over a year now.
like to look at this small piece of work, so that it can be closed in no time?
[I can pass on the info, with my filling (and corrections).]

**Comment by Andhrabharati** [comment]
@funderburkjim 
Here is the file I made in 2021--

### Guru-laghu unicode cahracters
laghu:	 ⌣ (AB)(U+2323), ᴗ (Wiki)(U+1D17),  ⏑ (Unicode)(U+23D1)
guru:	 − (AB)(U+2212) , – (Wiki)(en-dash),  ‒ recommended character (U+2012)

**Unicode Metrical symbols** (Brill,  Cardo, New Athena Unicode & Old Standford Indologique fonts render these characters)
`---------------------------------`
⏑ 	U+23D1 	D+F381 	METRICAL BREVE
⏒ 	U+23D2 	D+F382 	METRICAL LONG OVER SHORT
⏓ 	U+23D3 	D+F383 	METRICAL SHORT OVER LONG
⏔ 	U+23D4 	D+F384 	METRICAL LONG OVER TWO SHORTS
⏕ 	U+23D5 	D+F385 	METRICAL TWO SHORTS OVER LONG
⏖ 	U+23D6 	D+F386 	METRICAL TWO SHORTS JOINED
⏗ 	U+23D7 	D+F387 	METRICAL TRISEME
⏘ 	U+23D8 	D+F388 	METRICAL TETRASEME
⏙ 	U+23D9 	D+F389 	METRICAL PENTASEME

And the file containing the 126 lines is
[Ç lines filled (or corrected)- wiki style.txt](https://github.com/user-attachments/files/17007980/C.lines.filled.or.corrected.-.wiki.style.txt)

Now should other lines containing the "metrical symbols" also be changed accordingly?
