### ISSUE TITLE
Please specify a Sanskrit or and English word, not both

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/PWG#3]
If "Text Word:" means an English word, I would state that. Maybe. "Text Word (English, German):". I wanted to find the shortest headword that starts with "a" and ends with "h" and realised I can't do it on web, ok.
http://www.sanskrit-lexicon.uni-koeln.de/scans/PWGScan/2013/web/webtc2/index.php
![advanced](https://cloud.githubusercontent.com/assets/80761/4230117/a55bd86a-397e-11e4-8f58-004ba355c896.gif)

**Comment by drdhaval2785** [comment]
Now the world seems to have moved ahead a lot.
I tried with `a*h` and `suffix` settings in https://www.sanskrit-lexicon.uni-koeln.de/scans/PWGScan/2020/web/webtc2/index.php, and was amazed to see that now even regexes do work in search. Lovely.

```
1 अंह्
2 अक्षानह्
3 अक्ष्णयाद्रुह्
4 अद्रुह्
5 अनडुह्
6 अनड्वाह्
```

**Comment by funderburkjim** [comment]
Wow!

I never thought to try that.   In fact, we need to examine the php code to be sure we aren't
allowing arbitrary things,  since that can lead to security problems.

The relevant code is in csl-websanlexicon.
I've started an issue there.
OK for this PWG issue to be closed.

**Comment by gasyoun** [comment]
> In fact, we need to examine the php code to be sure we aren't
allowing arbitrary things, since that can lead to security problems.

Exactly.
