### ISSUE TITLE
aufschreien(?) -> aufschreien (?)

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/PWG#36]
In book there is space before `(?)`, lost here @funderburkjim 

`ati aufjauchzen, aufschreien(?): mṛgo nāśnoṃ ati yajjuguryāt Ṛv. 1, 173, 2.`

![fdsfdsdfssfdfsdfsd](https://user-images.githubusercontent.com/80761/115107558-41915b80-9f74-11eb-8b8b-0d2771707165.png)

**Comment by Andhrabharati** [comment]
There are more cases like this.

A dot after a number/ letter should have a space before another letter/ number coming.

If @funderburkjim agrees, one can help inserting the space in all such cases.

**Comment by Andhrabharati** [comment]
Looks like this issue is also closable, @funderburkjim !

**Comment by funderburkjim** [comment]
The opening topic of this issue looks to have been handled.

The 'dot followed by non-space'  are quite a different topic.
So closing this issue.
