### ISSUE TITLE
ls corrections for Spr. (II)

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/PWG#45]
The PWG dictionary has references to two editions of Boehtlingk's Indische Spruch:
* `Spr. (II) ...` for 2nd edition
* `Spr. I ...` for 1st edition.  (or more commonly Spr. 123)

This describes markup enhancements (and corrections) pertaining to the 2nd edition.
There are two standard forms of markup in pwg.txt which permit construction of urls to verses of a digitization of the 2nd edition.
* `<ls>Spr. (II) VX</ls>`  where V is a digit sequence representing the Verse number in Indische Spruch
* `<ls n="Spr. (II)">VX</ls>`

Before the corrections, 5308 instances of references were present in pwg.txt, and after the corrections 6949 references.

**Comment by funderburkjim** [comment]
For details of the process, see [pwg_ls2/spruch](https://github.com/sanskrit-lexicon/PWG/tree/master/pwg_ls2/spruch).

In particular, in addition to the 367457a commit, see
* [change_01.txt](https://github.com/sanskrit-lexicon/PWG/blob/master/pwg_ls2/spruch/change_01.txt)  lines changed in pwg.txt
* [listls_instances_SprII.txt](https://github.com/sanskrit-lexicon/PWG/blob/master/pwg_ls2/spruch/listls_instances_SprII.txt) the instances of 2nd edition references.

**Comment by funderburkjim** [comment]
## Spr. 1st edition
There are currently 8845 instances of `<ls>Spr. V...` where V is a digit sequence and is presumably
a reference to verse V in the 1st edition.

The first instance of `Spr. (II)` occurs in volume 6, under headword 'lamb', on page 6-0506.

**Comment by funderburkjim** [comment]
## Spr. (II) missed.
I just noticed that there are about 150 instances where 'Spr. (II)' is not marked as an 'ls reference.
This occurs in cases where the instance is part of a larger incorrectly marked fragment of references.
For example:
```
<ls>?2, 99, 25. GĪT. 11, 22. KĀM. NĪTIS. 1, 67. Spr. (II) 3454. 5456. 5457, v. l. KATHĀS. 10, 35. 50, 192.</ls> 
```

Will take a look at these. and make further corrections.

**Comment by funderburkjim** [comment]
Corrections mentioned in previous comment now made.
For details, see [change_02.txt](https://github.com/sanskrit-lexicon/PWG/blob/master/pwg_ls2/spruch/change_02.txt) and also the csl-orig commit 7740ff8.

**Comment by gasyoun** [comment]
> after the corrections 6949 references.

Should we believe that 500 are still missing? So every `Spruch` get a link?

**Comment by funderburkjim** [comment]
The goal is that every Spruch reference (2nd edition) gets a link, yes.  

> 500 are still missing?

Where did you get 500?   I think that only a handful of references to 'Spr. (II)' in PWG do not have links.

**Comment by gasyoun** [comment]
> The goal is that every Spruch reference (2nd edition) gets a link, yes.

Right. The last page states:

![fdsfdsdssfdfds](https://user-images.githubusercontent.com/80761/150703031-2ca595cd-d3e2-4e59-abde-3ae00f0f0e27.png)
