### ISSUE TITLE
ls markup corrections for pwg

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/PWG#46]
In work with #45,  noticed that there is a big amount of correction still needed in the `<ls>` markup of PWG.

This is a task that can be organized into several steps.  Some steps are almost mechanical, and some steps will require some greater understanding of exactly how to interpret Boehtlingk's text.   

I think we should attempt to do this markup improvement, due to the importance of PWG, and in particular to the significance of literary source references in this dictionary.

**Comment by gasyoun** [comment]
> importance of PWG, and in particular to the significance of literary source references in this dictionary.

It remains the first and biggest Sanskrit dicionary in the world.

**Comment by funderburkjim** [comment]
@gasyoun   The 'relatively mechanical' parts of this might be a good project for some of the student volunteers that you mentioned recently.

**Comment by gasyoun** [comment]
> The 'relatively mechanical' parts of this might be a good project for some of the student volunteers that you mentioned recently.

Show us the way - and they will follow.

**Comment by Andhrabharati** [comment]
@funderburkjim 

Is this issue closable now?

**Comment by funderburkjim** [comment]
Yes, closeable. Closing
