### ISSUE TITLE
[Printed book page 5-1383]

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/PWG#50]
@funderburkjim some are linked, some are not. Why?

![fsdfdsfsd](https://user-images.githubusercontent.com/80761/151626640-64bf0b6d-38fa-424a-8d05-9e7b4b75f67e.png)

https://sanskrit-lexicon.uni-koeln.de/simple/pwg/guru

**Comment by funderburkjim** [comment]
`[Page5-1384]` is now a link.
This currently only for pwg.
The links above show the changes in basicdisplay.php in csl-websanlexicon and csl-apidev repositories.

I think this responds to your concern.  If so, go ahead and close issue.

**Comment by drdhaval2785** [comment]
This deserves to be applied across dictionaries. Especially SKD and VCP have entries spanning multiple words. It would be great if we get the intermediate PDFs linked

**Comment by gasyoun** [comment]
> [Page5-1384] is now a link.

Thanks, it works. Why bold?

**Comment by funderburkjim** [comment]
## links nowhere 

Ouch!   I  had checked this for the basic display, but confirm that the links go to nowhere for simple search.

The link was ill-constructed. To confirm,  re-load pwg/guru in simple-search and click on the link.  It works now.

**Comment by funderburkjim** [comment]
@drdhaval2785 

This feature also works now for vcp, skd, and in fact for any other dictionary where that [Pagexxx] form appears in the text.  For example, see root हृ in dictionary MD.

In ap90 and mw dictionaries (perhaps others), such links are not generated; this may be due to either (a) the ap90.txt, etc or (b) to make_xml.py.  I haven't explored all the dictionaries.

**Comment by funderburkjim** [comment]
@gasyoun   Anything else needed from me before issue closing?

**Comment by Andhrabharati** [comment]
@funderburkjim 

This is what @gasyoun mentioned above.
> > If so, go ahead and close issue.
> 
> The links, if fixed, can be closed.

The other point he raised later (at the end of https://github.com/sanskrit-lexicon/PWG/issues/50#issuecomment-1024890949) ["is sg., du and pl. noted as such?"] can be covered while marking & expanding the abbr.s; so the issue can be closed now.
