### ISSUE TITLE
RGorr link target

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/PWG#53]
A link target for the Gorresio edition of Ramayana is now available for  review at
https://sanskrit-lexicon-scans.github.io/ramayanagorr

The url accepts a parameter for displaying the page containing a particulara kanda,sarga,verse.
For example
https://sanskrit-lexicon-scans.github.io/ramayanagorr/?1,70,4  displays the Gorresio page for
kanda 1, sarga 70, verse 4.

Currently, the images for volume 1 are available  (all of 1st kanda, sargas 1-9 of 2nd kanda).

The other 4 volumes, along with Gorresio uttrarakanda  are aimed to be available soon.

User comments on UI issues are requested.

**Comment by funderburkjim** [comment]
## links for pwg 
The displays for pwg now have active links for explicit literary sources marked as 'R. GORR.'.

For example, under kuSASva:
https://sanskrit-lexicon.uni-koeln.de/simple1.1a/pwg/kushashva/simple

There is still work to do to expose more active links for 'R. GORR.'

**Comment by funderburkjim** [comment]
## all pages present
The link target https://sanskrit-lexicon-scans.github.io/ramayanagorr now has all 2800+ pages.

The remaining task is to identify the 'bad' pages  (I know there are some, but a complete examination is needed).
and then provide replacements (from other sources) for the bad pages.

Note that this link target can stand on its own as a 'reader' for Ramayana.  Maybe we should have a link to it on the
sanskrit-lexicon home page?

Also, the display works fine  locally using the 'file:///'  protocol  (i.e., no server installation required).

**Comment by gasyoun** [comment]
> https://sanskrit-lexicon-scans.github.io/ramayanagorr/?1,70,4 displays the Gorresio page for
kanda 1, sarga 70, verse 4.

Why so small?

![cczcxzcxz](https://user-images.githubusercontent.com/80761/157973268-c1ddd92a-f82c-4c0e-b126-306425d0f66e.png)

**Comment by funderburkjim** [comment]
First comment -- This is how it looks in my (edge) browser.  The image in Firefox is similar.
![image](https://user-images.githubusercontent.com/6393033/157978472-aca4872c-7e91-4c52-b4e9-19654a5a2b60.png)

**Comment by funderburkjim** [comment]
2nd comment:
For checking pages, I made this version.  
Not only does it show the page, but the vertical size is greater.  
https://sanskrit-lexicon-scans.github.io/ramayanagorr/pagechk/index.html?1,70,4
![image](https://user-images.githubusercontent.com/6393033/157980108-eb85f271-e914-4299-a9f6-4a0d1062e538.png)

**Comment by funderburkjim** [comment]
I don't know why your image shows 2 copies, a little one and a bigger one.

**Comment by funderburkjim** [comment]
> Leave it to us.

Great!  I assume you're speaking for @KateRusse  or other?  (refer [pwg#83 comment](https://github.com/sanskrit-lexicon/PWK/issues/83#issuecomment-1065364551)).

The instructions are simple.  Just click each of the verse lines one at a time.  If the image is truncated so as to be unusable, then make a note of the volume and page  (e.g. rgorr_1.267.pdf).   Final result will be a list of those 
bad page notes.  From them, I'll find replacements.

**Comment by gasyoun** [comment]
> Not only does it show the page, but the vertical size is greater.

Thanks, but is still so small even if zoomed it, because the width of the page in Chrome. 

> Great! I assume you're speaking for @KateRusse or other? (refer https://github.com/sanskrit-lexicon/PWK/issues/83#issuecomment-1065364551).

Let us see, maybe @padmavatidd will understand how to do it even before @KateRusse get's here.

**Comment by funderburkjim** [comment]
> width of the page in Chrome

Here is screen shot using Chrome Browser.  I see no problem.  
So why are you having a viewing problem?  No idea.
Have you tried the 'fit to [age'/'fit to width' control in Chrome?
![image](https://user-images.githubusercontent.com/6393033/158001194-b3520236-6084-401f-ad40-ef5b05e5a75f.png)

**Comment by padmavatidd** [comment]
Ok, l'll do like this :)

>>You are identifying the pages for which better scans need to be sought.

Did I understand correctly that such bad printed pages are not a problem for you? 
[rgorr_2.223.pdf](https://github.com/sanskrit-lexicon/PWG/files/8280893/rgorr_2.223.pdf)
and I only need to find scan defects?

Don't you  plan to look at bad printed pages in other editions of the Ramayana? Or it's really not important?

**Comment by funderburkjim** [comment]
Pages such as rgorr_2.223.pdf ARE of interest -- Indeed all the pages you listed above are of interest.

For each such page, I will attempt to find a replacement from another source.  (e.g., if the page 
originally came from a Google Books version of Gorresio, I will try to find a replacement in the Bayer version of Gorresio),

The aim is to have each 1-page pdf to be legible.

**Comment by padmavatidd** [comment]
Okay, got it. will done :) namaskaraH 🙏

**Comment by padmavatidd** [comment]
Khanda 3 is perfect, other than the first 2 pages missing. So all numbers for reference because of the 2 missing pages is wrong.

**Comment by funderburkjim** [comment]
> So all numbers for reference because of the 2 missing pages is wrong.

Not sure I understand.   The first page for Khanda 3 shows as
`Kanda 3, Sarga 1, verses 1-6 (rgorr_3.003.pdf)`.   So you may be wondering about 3.001 and 3.002.
These two are a title page for Volume 3 and a blank page -- In particular they do not contain any
verses.   So the absence of links to these pages is not a problem here. 

Incidentally, the same is seen with `Kanda 1, Sarga 1, verses 1-1 (rgorr_1.003.pdf)`.

Glad the  Kanda 3 pages are perfect.

**Comment by padmavatidd** [comment]
Kanda 3, Sarga 1, verses 1-6 (rgorr_3.003.pdf) - actually there are verses 17-26
[rgorr_3.003.pdf](https://github.com/sanskrit-lexicon/PWG/files/8288661/rgorr_3.003.pdf)

**Comment by funderburkjim** [comment]
Oh,  So there is a problem with the indexing of Kanda 3.    I think I see what you mean now.

Will have to investigate further.  But agree there is some problem here.  Thanks for clarifying.

**Comment by Andhrabharati** [comment]
@funderburkjim 

I guess you could spend your time better by using my files posted at https://github.com/sanskrit-lexicon/PWK/issues/83#issuecomment-1063652494
[It is a matter of just few minutes, as compared to over a week that is spent till now and the effort is just mid-way still.]

These are all good pages from Google scans in my collection. **And there is no issue in my indexing.**

**All the issues being found and being reported above are wrt to other scan copies that you had used.**

**Comment by funderburkjim** [comment]
@Andhrabharati the kanda 3 problem is likely due to an error in my extraction/renaming.  Or in 
how I used your indexing file. 
I'll consider your posted files as a source of replacement pages.

**Comment by funderburkjim** [comment]
The kanda 3 problem now solved; it did turn out to be an error the extracting/renaming process.

Also minor verse-range correction in index at kanda 3, pages 5-6.  See commit above .

**Comment by funderburkjim** [comment]
The bad volume 2 (kanda 2) pages mentioned in [comment above](https://github.com/sanskrit-lexicon/PWG/issues/53#issuecomment-1069633573) have been replaced from the source mentioned in [this comment](https://github.com/sanskrit-lexicon/PWG/issues/53#issuecomment-1071171583).

**Comment by gasyoun** [comment]
> [It is a matter of just few minutes regenerating the page-wise pdf files, as compared to over a week that is spent till now and the effort is just mid-way still.]

Yeah, you love to see work being done twice, same work.

**Comment by padmavatidd** [comment]
4 Kanda - ok. Only one print defect - Kanda 4, Sarga 51, verses 10-19 (rgorr_4.085.pdf)

**Comment by padmavatidd** [comment]
please tell is it ok or not 
[rgorr_4.309.pdf](https://github.com/sanskrit-lexicon/PWG/files/8326953/rgorr_4.309.pdf)

**Comment by funderburkjim** [comment]
@padmavatidd  Will look for a better print for 4.309.

**Comment by padmavatidd** [comment]
5 kanda is good, all pages are understandable, but the following are not very nice:

**Comment by padmavatidd** [comment]
Kanda 5, Sarga 1, verses 77-86 (rgorr_4.141.pdf)
Kanda 5, Sarga 13, verses 50-59 (rgorr_4.203.pdf)
Kanda 5, Sarga 16, verses 50-55 (rgorr_4.225.pdf)
Kanda 5, Sarga 25, verses 10-19 (rgorr_4.257.pdf)
Kanda 5, Sarga 27, verses 20-29 (rgorr_4.269.pdf)
Kanda 5, Sarga 36, verses 10-19 (rgorr_4.308.pdf)
Kanda 5, Sarga 36, verses 20-29 (rgorr_4.309.pdf)
Kanda 5, Sarga 42, verses 15-20 (rgorr_4.341.pdf)
Kanda 5, Sarga 44, verses 8-14 (rgorr_4.347.pdf)
Kanda 5, Sarga 53, verses 20-29 (rgorr_4.375.pdf)
Kanda 5, Sarga 64, verses 1-9 (rgorr_4.416.pdf)
Kanda 5, Sarga 64, verses 10-19 (rgorr_4.417.pdf)
Kanda 5, Sarga 66, verses 30-34 (rgorr_4.424.pdf)
Kanda 5, Sarga 69, verses 1-9 (rgorr_4.432.pdf)
Kanda 5, Sarga 69, verses 10-19 (rgorr_4.433.pdf)
Kanda 5, Sarga 72, verses 20-21 (rgorr_4.441.pdf)
Kanda 5, Sarga 73, verses 60-66 (rgorr_4.448.pdf)
Kanda 5, Sarga 74, verses 1-9 (rgorr_4.449.pdf)
Kanda 5, Sarga 81, verses 10-19 (rgorr_4.471.pdf)
Kanda 5, Sarga 84, verses 1-9 (rgorr_4.481.pdf)
Kanda 5, Sarga 87, verses 1-9 (rgorr_4.489.pdf)
Kanda 5, Sarga 89, verses 45-54 (rgorr_4.500.pdf)
Kanda 5, Sarga 89, verses 55-64 (rgorr_4.501.pdf)

**Comment by gasyoun** [comment]
> Will look for a better print for 4.309.

@Andhrabharati any clue?

**Comment by Andhrabharati** [comment]
I had already said what I have to, at https://github.com/sanskrit-lexicon/PWG/issues/53#issuecomment-1071171583 (above),  @gasyoun!

And Jim very well knows what to do!!
[His reply to my above posting]
> I'll consider your posted files as a source of replacement pages.

**Comment by Andhrabharati** [comment]
Another week has passed after my above post; and two more Kandas are to be "seen" still (**one more week?**)!!

**Comment by padmavatidd** [comment]
whole 6 kanda is good

**Comment by padmavatidd** [comment]
7 kanda is entirely good

**Comment by gasyoun** [comment]
> Another week has passed after my above post; and two more Kandas are to be "seen" still (one more week?)!!

Happy now?

**Comment by funderburkjim** [comment]
All the Rgorr_4 pages mentioned [above](https://github.com/sanskrit-lexicon/PWG/issues/53#issuecomment-1076057761) have been replaced.

And the rest of the pages have been certified as good. 

So this task is completed! 

@padmavatidd   Thank you for the friendly help!  

And @Andhrabharati  Thank you for the good source of replacement pages.

**Comment by gasyoun** [comment]
>So this task is completed!

All kandas clean now?

**Comment by funderburkjim** [comment]
Yes.  AFAIK.
