### ISSUE TITLE
R. (Schlegel) link target

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/PWG#54]

**Comment by funderburkjim** [comment]
Link targets for Ramayana (Schlegel edition) now available for PWG.
`11538 matches in 11524 lines for "<ls>R\. [12]," in buffer: pwg.txt`

The target is https://sanskrit-lexicon-scans.github.io/ramayanaschl/.

The link for a specific verse adds query string `?kanda/sarga/verse`, e.g.,
https://sanskrit-lexicon-scans.github.io/ramayanaschl/?1,50,4

Which happens to occur under headword vAwa.

The links also are activated for PW.
`363 matches in 361 lines for "<ls>R\. [12]," in buffer: pw.txt`

As with Harivamsa and mbh-calcutta,  there is still work to do to uncover additional links, such as `<ls>R. 1, 2, 3. 2, 27, 10.</ls>`  where the first link (1,2,3) is active but not the second (2,27,10).

**Comment by gasyoun** [comment]
> As with Harivamsa and mbh-calcutta, there is still work to do to uncover additional links, such as <ls>R. 1, 2, 3. 2, 27, 10.</ls> where the first link (1,2,3) is active but not the second (2,27,10).

It's all around, including AV and RV. We have finalised work on AV and I will soon provide new links for them.

**Comment by funderburkjim** [comment]
Can we install  the new AV, RV at Github?

**Comment by drdhaval2785** [comment]
Closeable, @funderburkjim ?

**Comment by funderburkjim** [comment]
yes. Closing.

**Comment by gasyoun** [comment]
@funderburkjim 
https://samskrtam.ru/parallel-corpus/atharvaveda.html Russian comments added
https://samskrtam.ru/parallel-corpus/rigveda.html Russian comments added
