### ISSUE TITLE
Resolving the {?} places

### ISSUE THREAD

**Issue by Andhrabharati** [sanskrit-lexicon/PWG#66]
There are 7 such places (6 lines) in the text file.

`204440: <div n="2">— g) {%ein best. Metrum%} (4 Mal {Ç}{?} {Ç}{?}) `
`277743: <ls>HIT. 98, 11.</ls> — In den beiden letzten Bedd. offenbar = {?}`
`277749: {#waNkaka#}¦ <lex>m.</lex> {%gestempeltes%} {?} {%Silber, Silbergeld%} ({#rajatamudrA#}) `
`533545: <ls>KUMĀRAS. 3, 42.</ls> {#cOrajArarnif{?}BatEreva sTAtavyam#} `
`613960: <ls>H. 633.</ls> {#nAgnO mehaM#} {%(Urin%} oder {?} {%Urinlassen)%} {#kurvIta#} `
`651213: 1. {#utpulaka#}¦ ({#ud + pu°#}) <lex>n.</lex> {%das Sträuben der Härchen am Körper%} (vor Auf{?}sung): {#biBratyutpulakAni#} `

Out of these, the first two places (in a single line) belong to another issue - "filling up the prosodiac symbols" [#29]
204440 has to be made as 
`<div n="2">— g) {%ein best. Metrum%} (4 Mal ¯ ˘ ¯ ˘ ¯ ˘ ¯ ˘ ¯ ˘ ¯ ˘ ¯ ˘ ¯ ˘ ¯ ˘ ¯ ˘)`
[Hope @funderburkjim might be interested in filling up the rest of such 126 lines as well; and I can provide the file I have made in May 2021 itself, if he wants]

277743 should have no such mark, as the item is a "protruding image" from the folowing entry and has to be made as 
`<ls>HIT. 98, 11.</ls> — In den beiden letzten Bedd. offenbar =`

277749 should have the item replaced with the image (denoting the regnal stamp) [{#**rajatamudrA**#}]
![image](https://user-images.githubusercontent.com/75209130/216750921-19a54c67-59c0-4b7e-93e6-2e8da8b7fb0f.png)
and is to be made something like 
`{#waNkaka#}¦ <lex>m.</lex> {%gestempeltes%} <img>xxx</img> {%Silber, Silbergeld%} ({#rajatamudrA#})`

533545 has a print error (wrong placement of f-mAtrA mark etc. wrt the Kosegarten's book)
![image](https://user-images.githubusercontent.com/75209130/216756848-c9439a6e-f5c2-417d-998c-b576aae8f1a3.png)

 and is to be made as
`<ls>KUMĀRAS. 3, 42.</ls> {#cOrajArErniBftEreva sTAtavyam#}`

613960 the Cologne scan has a missing at this place and is to be made as
`<ls>H. 633.</ls> {#nAgnO mehaM#} {%(Urin%} oder {%das Urinlassen)%} {#kurvIta#}`
[This shows that I have a GOOD source (scan and print) with me!!]

651213 the Cologne scan has a missing at this place and is to be made as
`1. {#utpulaka#}¦ ({#1. ud + pu°#}) <lex>n.</lex> {%das Sträuben der Härchen am Körper%} (vor Aufregung): {#biBratyutpulakAni#}`
[This shows that I have a GOOD source (scan and print) with me!!]

**Comment by gasyoun** [comment]
> should have the item replaced with the image (denoting the regnal stamp)

non-Unicodable text?

> [This shows that I have a GOOD source (scan and print) with me!!]

And a bright head

**Comment by Andhrabharati** [comment]
> 277749 should have the item replaced with the image (denoting the regnal stamp) [{#**rajatamudrA**#}]
> ![image](https://user-images.githubusercontent.com/75209130/216750921-19a54c67-59c0-4b7e-93e6-2e8da8b7fb0f.png)
> and is to be made something like
> `{#waNkaka#}¦ <lex>m.</lex> {%gestempeltes%} <img>xxx</img> {%Silber, Silbergeld%} ({#rajatamudrA#})`



> > should have the item replaced with the image (denoting the regnal stamp)
> 
> non-Unicodable text?

@gasyoun 

I got reminded of this, when looking at the Mongolian word in the other issue .

This also appears to be a Mongolian word (this time written top-to-bottom!), tañga (ᠲᠠᠩᠭᠠ)
![image](https://github.com/sanskrit-lexicon/PWG/assets/75209130/1c151d3a-c5c2-410d-81e0-8ed8b23aa678)

Could you pl. get this checked and confirmed by your Mongolian friend?

**Comment by Andhrabharati** [comment]
@gasyoun 
Would you pl. get your Mongolian friend's opinion on the above?

@funderburkjim 
This is a very small work for you to attend and close in no time.

**Comment by Andhrabharati** [comment]
@funderburkjim 

Here are the 5-0907 and 5-1165 pages from the scans I use--
[pwg5-1165 (Bavarian).pdf](https://github.com/user-attachments/files/17008048/pwg5-1165.Bavarian.pdf)
[pwg5-0907 (Bavarian).pdf](https://github.com/user-attachments/files/17008050/pwg5-0907.Bavarian.pdf)

But you might like to have the B&W pages from the MLBD 1990 print of the Japanese 1976 edition--
[pwg5-0907.pdf](https://github.com/user-attachments/files/17008036/pwg5-0907.pdf)
[pwg5-1165.pdf](https://github.com/user-attachments/files/17008037/pwg5-1165.pdf)
