### ISSUE TITLE
Verz. D. Oxf. H. links

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/PWG#69]
Refer: https://github.com/sanskrit-lexicon/PWG/issues/37#issuecomment-882338955
for a link scan of "Catalogi codicum manuscriptorum Bibliothecae Bodleianae" by Aufrecht.

Here is the [link](https://archive.org/download/catalogicodicumm81bodl/catalogicodicumm81bodl.pdf)

@Andhrabharati  - you mention "Checked few citations in PWG and they all tallied perfectly with this book's content."

I've now downloaded the scan (appears good quality).

Here is my understanding of  how the references in PWG correspond to the scan, based on one example.

Under laGujAtiviveka in PWG, there is reference `<ls>Verz. d. Oxf. H. 278,a,36.</ls>`

On internal page 278, column a, line 36 there is a mention of `Laghujativiveka`.  

So the link would construct a reference to pg_278 .

Is this example typical ?

<img width="704" alt="image" src="https://github.com/sanskrit-lexicon/PWG/assets/6393033/30099c1f-6a4c-4047-9f6e-f82d70c94b40">

**Comment by funderburkjim** [comment]
Also, what can one do with that reference?  What does the '157a'  refer to ?

**Comment by funderburkjim** [comment]
From the title page, "Catalogi codicum manuscriptorum Bibliothecae Bodleianae" by "Th. Aufrecht".

The PWG references are shown as "Verz. d. Oxf. H."  What does this German abbreviation expand to?

I plan to put the link target page pdfs in a Github repository (under the sanskrit-lexicon organization).
 What to name that repo?  maybe **catalogi_aufrecht** ? 

How is this related to ACC (Aufrecht Catalogus Catalogorum ?

**Comment by Andhrabharati** [comment]
> So the link would construct a reference to pg_278 .
> 
> Is this example typical ?

Yes, it is!

> Also, what can one do with that reference? What does the '157a' refer to ?

We have nothing to do with those internal numbers (which refer to the folio number etc. of the particular manuscript), at least AS OF NOW!!

> The PWG references are shown as "Verz. d. Oxf. H." What does this German abbreviation expand to?

Let's have it as in pwk -- AUFRECHT, Verzeichniss der Oxforder Handschriften, 1864.
In the process of deciphering the biblio (ls) entries) in the PWG, I had noticed that at some more places the "Title of a work" is "translated into German" in PWG, while there was no such German edition ever [the actual/original work being in a different language altogether]!!

There are more of such Verzeichniss [which I would translate as "Descriptive Catalogue"] from various "collection centers" [Libraries] across Europe that were cited in PWG, namely
 Berlin [by Weber, 1853],
 Cambridge [by Aufrecht, 1869],
 Kopenhagen [by Westergaard, 1846],
 Petersburger [by Boethlingk, 1846],
 Tübingen [by Roth, 1865]

As I had mentioned elsewhere earlier, it was Weber who had "shown" how a descriptive catalogue should be "made" (in his Berlin Catalogue) [thereby paved a way of doing the same], which is followed by almost all the subsequent Des. Cat.s anywhere across the globe.

> How is this related to ACC (Aufrecht Catalogus Catalogorum ?

Over 50+ years, quite many Skt. manuscript catalogues across the globe have been generated and it became a cumbersome activity to browse through them to get "information" about a particular work; this prompted Aufrecht (1891) to make a "Catalogue of Catalogues", picking up concise info from various catalogues across Asia, Europe and America; and it contained all the above Verzeichniss (of PWG) and many more catalogues!! [This is popularly referred to as Aufrecht's Catalogus Catalogorum (**ACC**)]

And the similar work is again taken up by University of Madras (India) to make the [New Catalogus Catalogorum](https://www.unom.ac.in/index.php?route=department/department/deptpage&deptid=64) (NCC) in 1935, that took account of of all subsequent Skt. catalogues published (or prepared) after ACC.
[This has appeared in 42 volumes (1937-2019, 80+ years) in total.]
**And it is not out of place to note that the NCC has included Buddhistic, Jain and Prakrit works as well (as against ACC, which is limited to Sanskrit alone).**

**Comment by Andhrabharati** [comment]
> I plan to put the link target page pdfs in a Github repository (under the sanskrit-lexicon organization).
> What to name that repo? maybe **catalogi_aufrecht** ?

Some time in future, if (and when) we try to also link the Trinity Library catalogue (at Cambridge) [again by Aufrecht], there would be a conflict.
So I would prefer using the more suggestive name "Oxf_Cat_Aufrecht" here.

**Comment by funderburkjim** [comment]
## sch
28 instances of *Verz. d. Oxf. H.* literary source.
Modification: `ls>Verz. d. Oxf. H.</ls> 248, b, 36.`  -> `ls>Verz. d. Oxf. H. 248, b, 36.</ls>`

So these will be linkable in Schmidt.

**Comment by funderburkjim** [comment]
https://github.com/sanskrit-lexicon-scans/Oxf_Cat_Aufrecht  is repository for pdf images.

Also Github pages activated.

A simple html application.

A link to page 123 is https://sanskrit-lexicon-scans.github.io/Oxf_Cat_Aufrecht/index.html?123

The page can be 1 to 578.

**Comment by funderburkjim** [comment]
Various repos revised so the links will be active in displays.  See the above commits for details.

**Comment by Andhrabharati** [comment]
Other than the three "pw works" (PWG, pwk and SCH), it is only ACC that refers to this Oxf. Catalogue (but it may not required to be "linked" with its sources).

**As such this issue has served its purpose and can be closed now.**
