### ISSUE TITLE
Standardization of pwg links for KATHĀS.

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/PWG#71]
The 'normal' markup for PWG dictionary of a reference to Katha-sarit-sagara has the form
`<ls>KATHĀS. t, s.</ls>`  , where t is the taranga number and s is the shloka number (both are digit sequences).
In a display for pwg, this form generates a link to the cdsl link target for Katha-sarit-sagara , as discussed in #70.
Other activated link forms are
`<ls n="KATHĀS.">t, s.</ls>`  and `<ls n="KATHĀS. t,">s.</ls>`

But there are many 'implied' forms whose markup can be changed to a sequence of these normal forms.
For instance,  `<ls>KATHĀS. 12, 33. 17, 17. 19, 50</ls>` generates a link for 12,33  but not for 17,17 or 19,50.

This example can be recoded in pwg.txt as 
`<ls>KATHĀS. 12, 33.</ls> <ls n="KATHĀS.">17, 17.</ls> <ls n="KATHĀS.">19, 50</ls>` 

In this recoding, 17,17 and 19,50 are active links.
This issue describes work that recodes most of these implied forms.

**Comment by gasyoun** [comment]
> This issue describes work that recodes most of these implied forms.

Work done?

**Comment by Andhrabharati** [comment]
Not done yet; when done, the KSS ls-links count would increase from 14k to 21k!!

**Comment by funderburkjim** [comment]
## work finished
See [issue71 files](https://github.com/sanskrit-lexicon/PWG/tree/master/pwgissues/issue71).

The readme file shows details.

Some stats:
* 2538 lines of pwg changed
* The changes were done in 3 steps:
  * change_1.txt 2167 lines changed  (by program)
  * change_2.txt  146 lines changed   (by program)
  * change_3.txt   230 lines changed  (manual)
* start with 19502 individual  KATHĀS ls refs (linksort1_0.txt)
* finish with 25005 references (linksort1_3.txt)
  * All but 15 of these are 'linkable'
    * 8 are parameter-less (`<ls>KATHĀS.</ls>`)
    * 7 have non-linkable parameters -- see linksort3_3.txt  
      * one of these is in the pdf, but within an 'Einl.' of a taranga, rather than a shloka.
 
I think this issue can be closed now.
