### ISSUE TITLE
Manu-smfti link target

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/PWG#73]
Steps in creating a link target for **Lois de Manou** with Notes by *Loiseleur Deslongchamps* (Paris 1830).

12331 matches in 12306 lines for "<ls>M\. " in buffer: pwg.txt

**Comment by funderburkjim** [comment]
@Andhrabharati  Would you upload your indexing (as mentioned in [this link in issue 70](https://github.com/sanskrit-lexicon/PWG/issues/70#issuecomment-2333676928) ?

**Comment by Andhrabharati** [comment]
Glad that you asked for my file!

Here it is (as a tab-delimited text)--
[Manu (Deslongchamps) index.txt](https://github.com/user-attachments/files/16911338/Manu.Deslongchamps.index.txt)

**Comment by Andhrabharati** [comment]
BTW, I did not check if any reference is there to the Notes by Deslongchamps (pp. 311-560), or the additions & corrections (pp. 561-7) and did not make any index of those pages.

They can also be indexed, if we come acorss any such instances.

**Comment by Andhrabharati** [comment]
> 12331 matches in 12306 lines for "M. " in buffer: pwg.txt

And, the count would increase by another 50%, once the series of (dot-separated) citations are split as individual ones!

**Comment by funderburkjim** [comment]
## other dictionaries?

@Andhrabharati   I noticed that we apparently activated kss links for pwg, pw, pwkvn, sch. 
Same list of dictionaries for manu?

**Comment by Andhrabharati** [comment]
Yes, and yoy missed MW!!

**Comment by funderburkjim** [comment]
## link target constructed

pdf pages are here: https://github.com/sanskrit-lexicon-scans/manu/blob/main/

Application urls:
* By adhyaya,shloka: https://sanskrit-lexicon-scans.github.io/manu/?3,5
* By (pdf) page: https://sanskrit-lexicon-scans.github.io/manu/?page=8

The Cologne dictionaries will link using the adhyaya,shloka url form.

Next step is to modify the cologne displays to use this link target.  
This will be done first for pwg.

**Comment by Andhrabharati** [comment]
It appears that the pdf is used (as-is) with external page numbers (cover-to-cover)!

**Comment by funderburkjim** [comment]
Yes.  The reason the '?page=N' parameter for displays was written was so that other 
applications could be written, to make use of 'Notes' and 'Corrections' sections.

And the reason for the next/prev page controls was so that shlokas starting on one page and
ending on the next page would be fully available.

**Comment by Andhrabharati** [comment]
>> It appears that the pdf is used (as-is) with external page numbers (cover-to-cover)!

> Yes. The reason the '?page=N' parameter for displays was written was so that other
> applications could be written, to make use of 'Notes' and 'Corrections' sections.

I understand that; but, my point is how would one know which page to ask for, if he wants to go to p. 421 of the text to see the notes on Sl. 124 (without the index); the external page number is not at all in the vicinity (far away by 41 pages).
He should somehow "identitify" that the page number has to be incremented by 41, to reach there!

**Comment by funderburkjim** [comment]
## finish this issue

Work and notes are [here](https://github.com/sanskrit-lexicon/PWG/tree/master/pwgissues/issue73).

It remains to 'standardize' all the 'M.' ls references in pwg.txt.  This will be done in another issue.
Closing this issue.

**Comment by funderburkjim** [comment]
> ...  which page to ask for,  ...

Sure, there could be some other application that exposes all the notes.
Maybe you know someone who could write such an app.

The only current use of the ?page=N option is for the prev/next page UI element that 
occasionally is needed to see a full shloka that is partly at the end of one page and
partly only the next page.
