### ISSUE TITLE
Remove gratuitous spaces in ls

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/PWG#77]
This is in response to [this comment](https://github.com/sanskrit-lexicon/PWG/issues/57#issuecomment-2353169025).

I

**Comment by funderburkjim** [comment]
Will change space between comma and digit within scope of an `<ls...</ls>`, as was preferred in above comment.

Most lines of pwg.txt have a space at the end, which serves no purpose currently; so removing the ending space.

These two changes modify over half of the million-plus lines of pwg.txt.

**Comment by Andhrabharati** [comment]
Excellent; I would also request Jim to remove the blank lines within the body matter (mostly preceding the ls or div breaks). [A blank line should only be present between two entries (or at the header H-lines), as a NORM.]

There are about 13k of such blank lines on the whole.

**Comment by Andhrabharati** [comment]
> Most lines of pwg.txt have a space at the end, which serves no purpose currently; so removing the ending space.

These are all at the (artificial) line-splitiing introduced at <ls (~500k), <div (~100k) and <is (94) tags!

**Comment by funderburkjim** [comment]
This cleanup completed.
[work directory](https://github.com/sanskrit-lexicon/PWG/tree/master/pwgissues/issue77).

Summary:
* the two changes mentioned [above](https://github.com/sanskrit-lexicon/PWG/issues/77#issuecomment-2359352892)
* remove blank lines within an entry (16000 of these)
* remove [Pagev-xxxx] lines outside entries  (3232 of these)
* remove extra blank lines outside of entries (138 of these)
* a handful of misc. changes

The lines outside of entries can be summarized as:
* H-line, blank-line precede first entry
* no line after LEND line of last entry
* A single empty line between LEND and metaline for 122661 entries
* For 74 entries, H-lines with blank line as per file analyze_between.txt

grep -E '^<L>' temp_pwg_5.txt | wc -l
122736  entries 
= (+ 1 122661 74)

**Comment by Andhrabharati** [comment]
@funderburkjim 
> * remove [Pagev-xxxx] lines outside entries  (3232 of these)

There still remain 3 instances where a [Pagev-xxxx] line precedes the LEND line, that are of same nature as the above criterion.
**These could also be removed.**

Also found some misc. cases that need correction:
`>[^<]*>`: [36 instances]
`^[^<]*>`:  [3 instances]

And the 85 cases of "more than a single space together", ` [ ]+`, could also be corrected.

**Comment by Andhrabharati** [comment]
I am glad that Jim has put his "first-step" in getting the digital text closer to the PWG print.

**Comment by Andhrabharati** [comment]
Seen that I had split two entries 63080 & 79329 into two parts each, making them look more "meaningful".

CDSL:	`<L>63080<pc>5-0966<k1>atrijAta<k2>atrijAta<h>12`
AB:	`<L>63080<pc>5-0966<k1>atrijAta<k2>atrijAta<h>1`
	`<L>63080.1<pc>5-0966<k1>atrijAta<k2>atrijAta<h>2`	

![image](https://github.com/user-attachments/assets/8bb2c263-eb7a-4d26-aad0-521850cf36e1)
`------------------------------------------`
CDSL:	`<L>79329<pc>5-1624<k1>pradoza<k2>pradoza<h>23`
AB:	`<L>79329<pc>5-1624<k1>pradoza<k2>pradoza<h>2`
	`<L>79329.1<pc>5-1624<k1>pradoza<k2>pradoza<h>3`

![image](https://github.com/user-attachments/assets/0c2c9e29-95d1-4b96-85fc-80a6bf85c382)

**Probably, Jim might not disagree doing thus in the cdsl file.**

**Comment by Andhrabharati** [comment]
Dear Jim,

Now that you've reopened this issue, you might consider [this](https://github.com/sanskrit-lexicon/PWG/issues/34#issuecomment-2351966964) point as well!

**Comment by funderburkjim** [comment]
## AB addtional changes

Per above suggestions. Jim notes in [issue77 readme](https://github.com/sanskrit-lexicon/PWG/tree/master/pwgissues/issue77) at `09-20-2024  Reopened. Further corrections from AB`.

Jim will consider the `hyphens em-dashes en-dashes` point next.

**Comment by Andhrabharati** [comment]
Thank you, Jim; now this issue can be closed again!

**Comment by funderburkjim** [comment]
hyphen to em-dash changes made.
github and cologne revised.

Many improvements made to cdsl pwg, thanks to @Andhrabharati suggestions,  and his followup of some 3.5 year old suggestions from @gasyoun .

@Andhrabharati  I suspect many of these changes have the side-effect of decreasing the diff between your version(s) and the cdsl version of pwg.  Perhaps there are other 'discrete' (well-defined) changes that cdsl could tackle now?  If so these can be taken up, in new issues or in existing issues which have been neglected by cdsl.

**Comment by Andhrabharati** [comment]
> Many improvements made to cdsl pwg, thanks to @Andhrabharati suggestions
> 
> @Andhrabharati I suspect many of these changes have the side-effect of decreasing the diff between your version(s) and the cdsl version of pwg.
>
> Perhaps there are other 'discrete' (well-defined) changes that cdsl could tackle now? If so these can be taken up, in new issues or in existing issues which have been neglected by cdsl.

Thank you Jim, for appreciating my work.
It is not a side-effect (of decreasing the diff. between AB and CDSL works), but some deliberate stepping towards matching the PWG's "intended" (undocumented) theme and presentation.

And yes, **there are quite many refinements in my version** that could (and should) be carried into the cdsl version.
But, that would be a "long journey" (may be taking 4-6 months), when done in a step-by-step fashion.
May be we can do it in parts, taking breaks in-between for attending to other tasks as well.

If you are serious and willing, I can make and post an initial version (with sufficient details of working) for you to start with.

**Comment by funderburkjim** [comment]
Systematic attention to pwg is a worthwhile goal.

Incorporation of digitizations of the missing VN (#76) should be done first.

Then posting of your initial version.  

Agree?

**Comment by Andhrabharati** [comment]
And probably after the AES "revision", which is more less a very straight-forward and easy work (from my version).

**Comment by gasyoun** [comment]
> And probably after the AES "revision", which is more or less a very straight-forward and easy work (from my version).

Makes sense -- just to finish it.
