### ISSUE TITLE
accents.html PWG Accents

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/PWG#9]
Comments on http://www.sanskrit-lexicon.uni-koeln.de/scans/PWScan/2014/web/webtc1/help/accents.html

1) http://www.sanskrit-lexicon.uni-koeln.de/scans/PWScan/2014/web/webtc/help.html has Last modified: March 31, 2014; http://www.sanskrit-lexicon.uni-koeln.de/scans/PWScan/2014/web/webtc1/help/accents.html has none. 

2) After https://github.com/sanskrit-lexicon/Cologne/issues/38 this text is in several places outdated.

3) "This document was written with the PWG accents." - Is there a place other than the homepage where it's explained who is PWG? I mean just 100 years ago same work was called BR., pw and in five more ways. Nowadays you call PWK = PW, so everything changes and new readers will not be able even to decipher it.

4) Why not name the whole document "PWG Accents"? 

5) "Parts of it may not apply to Pune Dictionary." now I know 1 out of 2 lost treasures. I could not even home that the 1 page I saw was not the only one around.

6) nyu^ptA a\kzA anu^ dI\va A^san - "\" can occur only in the text. That is not easy to understand, was first looking for it in headings.

7) Bohtlingk -> Boehtlingk -> Böhtlingk. Even in Russian it's Бётлинк, нот Ботлинк. We are rich enough to use the right form Böhtlingk.

8) "simply translates the encoding marks into available characters" - if you would approach Siddhanta's author, he might fine tune some hinting and the "u" as the printed dictionary has it could be displayed correctly. It's already there, in the font, maybe

9) When you say "it does no accent sandhi or interpretation" you mean "Devanagari 'u' above the udAtta vowel", if so - read three times to understand who is "it". It is the headword hero. I would even make the word headword bolded.

10) "uncommon Kashmiri marks" - do we have a list of screenshots of them? Same as point 8, doable. Otherwise the site will always remain "under development".

11) "The following table shows screen shots" is if not outdated, at least a variant only. 

12) "Warning: The Devanagari display of the svarita generally requires the installation of the praja_Vedic font" - I would make it less "warning", because if late 2014 it's no more an issue anyway.

13) Go for Siddhanta-Calcutta instead of just Siddhanta. All we have to do is instead of the usual \u0951 form use the "graph" from \u0951. Need hinting is implemented (it will not collide with other lettes, it will move to the left from them.). Siddhanta-Calcutta uses the "a" that is graphically similar to Petersburger "French" devanagari font. We can prefer it instead of the default Siddhanta font. It's there in F193 position.

See https://github.com/sanskrit-lexicon/PWG/blob/master/PWG-accents.pdf

**Comment by gasyoun** [comment]
Sergiy Tkachenko

**Comment by drdhaval2785** [comment]
@gasyoun Time for review of open and closed questions?

**Comment by Andhrabharati** [comment]
@drdhaval2785 
This is closable now, I guess, with the PWG accents been worked by Jim recently (at my intervention).

**Comment by drdhaval2785** [comment]
Great.
